version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    volumes:
      - ./keycloak/realm-import:/opt/keycloak/data/import:ro
    networks:
      - public-network
      - app-network

  keycloak-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - identity-data-network

  api-gateway:
    image: api-gateway:local
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    depends_on:
      - keycloak
    ports:
      - "8079:8080"
    environment:
      GATEWAY_JWT_ISSUER_URI: http://keycloak:8080/realms/demo-realm
      PRODUCT_SERVICE_URI: http://product-service:8082
      ORDER_SERVICE_URI: http://order-service:8084
      PAYMENT_SERVICE_URI: http://payment-service:8085
    networks:
      - public-network
      - app-network

  product-service:
    image: product-service:local
    build:
      context: .
      dockerfile: product-service/Dockerfile
    depends_on:
      - keycloak
    environment:
      PRODUCT_JWT_ISSUER_URI: http://keycloak:8080/realms/demo-realm
    ports:
      - "8082:8082"
    networks:
      - app-network

  order-service:
    image: order-service:local
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on:
      - keycloak
      - product-service
    environment:
      ORDER_JWT_ISSUER_URI: http://keycloak:8080/realms/demo-realm
      ORDER_CLIENT_TOKEN_URI: http://keycloak:8080/realms/demo-realm/protocol/openid-connect/token
      ORDER_CLIENT_ID: order-service-client
      ORDER_CLIENT_SECRET: order-service-secret
      PRODUCT_SERVICE_BASE_URL: http://product-service:8082
    ports:
      - "8084:8084"
    networks:
      - app-network

  payment-service:
    image: payment-service:local
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    depends_on:
      - keycloak
      - order-service
    environment:
      PAYMENT_JWT_ISSUER_URI: http://keycloak:8080/realms/demo-realm
      ORDER_SERVICE_BASE_URL: http://order-service:8084
    ports:
      - "8085:8085"
    networks:
      - app-network

  frontend-react:
    image: frontend-react:local
    build:
      context: ./frontend-react
    depends_on:
      - api-gateway
      - keycloak
    ports:
      - "3000:3000"
    networks:
      - public-network

networks:
  public-network:
  app-network:
  identity-data-network:

volumes:
  keycloak-db-data:
