server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${PAYMENT_JWT_JWK_SET_URI:http://localhost:8081/realms/demo-realm/protocol/openid-connect/certs}

services:
  order-service-base-url: ${ORDER_SERVICE_BASE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
