server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${PRODUCT_JWT_JWK_SET_URI:http://localhost:8081/realms/demo-realm/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info
